### ISSUE TITLE
Write tests for InMemoryExperimentRepo

### ISSUE THREAD

**Issue by dpolansky** [cpe305/fall2016-project-dpolansky#4]
Add tests for the `InMemoryExperimentRepo` class:

- test creating an experiment
- test getting all experiments
- test getting experiment by id
- test getting experiment by id properly throws a `NotFoundException`
- test deleting an experiment
- test deleting an experiment by id properly throws a `NotFoundException`

To ensure that each test has a fresh instance of the repo, use the `@Before` JUnit annotation to define a beforeTest method that re-instantiates the repo. There's an example of this in the `TestExperimentServiceImpl` class.

info on testing that an exception is thrown: http://stackoverflow.com/questions/156503/how-do-you-assert-that-a-certain-exception-is-thrown-in-junit-4-tests

**Comment by cesiu** [comment]
Did you add me as a collaborator? I'm getting a 403 when I try to push.

**Comment by dpolansky** [comment]
You should be able to just make a pull request -- is it not working?

**Comment by cesiu** [comment]
Ah, you wanted fork and pull request instead of branch and pull request. Got it. (I was assuming we were supposed to do branches because I vaguely remember Professor Socher telling us we had to add each other as collaborators.) Made the request. Travis is passing.

**Comment by cesiu** [comment]
I didn't mock anything in the tests since the only dependency is the Experiment class, which I saw you went ahead and used without mocking for the existing TestExperimentServiceImpl tests.

**Comment by dpolansky** [comment]
Implemented in 4585dbc35cd6e689017bb9e955e9131aa6fc6ead
